version: "3.9"

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "valore"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - shared-network

  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "valore"
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_MONGODB_PORT: "27017"
    depends_on:
      - db
    ports:
      - "8081:8081"
    networks:
      - shared-network

networks:
  shared-network:

volumes:
  mongodb_data_container: