name: Build CI

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
      - name: typecheck electron
        run: yarn electron:compile
      - name: run lint
        run: yarn lint